name: MEW_BACKEND
on:
  push:
    branch:
      - main

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}


jobs:
  echoing:
    runs-on: self-hosted
    steps:
      - run: echo "Running jobs on self hosted runner"

  deploy_test:
    needs: echoing
    runs-on: self-hosted
    steps:
      - run: gcloud compute ssh --command 'whoami' mew-backend-production-vm-01 --zone us-central1-a

  build:
    needs: deploy_test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create-Build
        id: create-build
        run: "export PATH=$PATH:/home/gagan/go/bin:$GOPATH && mkdir artifact && go build -o ./artifact && cp -r migrations ./artifact/"


      - name: Set-Artifact-Name
        id: artifact-name
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.artifact-name.outputs.short_sha }}"

      - name: Uploading Artifact
        uses: google-github-actions/upload-cloud-storage@v1

        with:
          path: 'artifact/'
          destination: 'mew_backend_artifacts/artifact_${{ GITHUB_SHA }}'
